name: UWP Build and Package

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Restore NuGet packages
        run: nuget restore

      - name: Build UWP project
        run: msbuild /t:Restore,Build /p:Configuration=Release /p:Platform=x86 EldenTracker.csproj

      - name: Create app package
        run: msbuild /t:Package /p:Configuration=Release /p:Platform=x86 EldenTracker.csproj
